Category.delete_all
cats = [
    'Accounting',
    'Advisors',
    'Analytics',
    'Blockchain',
    'Bootstrapping',
    'Business development',
    'Business models',
    'Compensation',
    'Customer discovery',
    'Design',
    'Developers',
    'Entrepreneurship',
    'Equity',
    'Experiments',
    'Finance',
    'Founders',
    'Funding',
    'Growth',
    'Ideation',
    'Internationalization',
    'Leadership',
    'Lean startup',
    'Legal',
    'Marketing',
    'Mentors',
    'Online advertising',
    'Operations',
    'Partnerships',
    'Planning',
    'Pricing',
    'Product/Market fit',
    'Product management',
    'Productivity',
    'Recruiting',
    'Revenue models',
    'Sales',
    'Software engineering',
    'Strategic partnerships',
    'Team',
    'UX/UI'
]
cats.each do |c|
  Category.create(name: c)
end