source 'https://rubygems.org'

ruby                                        '2.3.3'
gem 'rails',                                '>= 5.0.1', '< 5.1'
gem 'pg',                                   '~> 0.18'

# gem 'aasm'
gem 'acts-as-taggable-on'
gem 'acts_as_votable',                       '~> 0.11.1'
gem 'actionview-encoded_mail_to'
gem 'activeadmin'
gem 'activeadmin_quill_editor'
gem 'ancestry'
# gem 'active_record_union'
# gem 'ajax-datatables-rails'
# gem 'analytics-ruby',                       '~> 2.0.0', require: 'segment/analytics'
gem 'audited'
gem 'bitmask_attributes'
# gem 'bulk_insert'
gem 'cancancan'
gem 'coffee-rails',                         '~> 4.1.0'
gem 'country_select', require: 'country_select_without_sort_alphabetical'
gem 'dalli'
gem 'devise'
gem 'faraday'
gem 'gibbon'
gem 'font-awesome-rails'
# gem 'foundation-icons-sass-rails'
gem 'foundation-rails',                     '6.3.1'
gem 'icalendar'
gem 'inherited_resources', github: 'activeadmin/inherited_resources'
# gem 'intercom-rails'
gem 'jbuilder',                             '~> 2.0'
# gem 'jquery-datatables-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'kaminari'
# gem 'koala'                               # Facebook
# gem 'mechanize'
# gem 'newrelic_rpm'
# gem 'omniauth-facebook'
# gem 'omniauth-twitter'
# gem 'omniauth'
# gem 'nokogiri'                              # for premailer-rails
gem 'paranoia'
gem 'pg_search'
# gem 'premailer-rails'                       # needs nokogiri
gem 'pretender'
gem 'quilljs-rails'
gem 'rack-attack'
gem 'rails_autolink'
# gem 'rails-jquery-autocomplete'
# gem 'rails-ujs'
# gem 'redactor-rails'
gem 'redcarpet'
# gem 'redis',                                '~> 3.0'
# gem 'redis-namespace'
gem 'route_downcaser'
# gem 'sanitize'
gem 'sass-rails',                           '~> 5.0'
gem 'scout_apm'
gem 'seedbank'
# gem 'sidekiq'
gem 'simple_calendar'
gem 'simple_form'
# gem 'sidekiq'
# gem 'sinatra'
gem 'slim-rails'
# gem 'smarter_csv'
# gem 'socialization'
# gem 'split',                                require: 'split/dashboard'
gem 'stripe'
# gem 'twitter'
gem 'uglifier',                             '>= 1.3.0'
gem 'unread'
gem 'validate_url'
# gem 'video_info'

group :development do
  gem 'awesome_print'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'guard'
  gem 'guard-livereload',                   '~> 2.4', require: false
  gem 'html2slim'
  gem 'letter_opener'
  gem 'listen',                             '~> 3.0.5'
  gem 'pry'
  gem 'puma'
  # gem 'puma',                               '~> 3.0'
  gem 'rack-livereload'
  gem 'spring'
  gem 'spring-watcher-listen',              '~> 2.0.0'
  gem 'web-console'
end

group :test do
  # gem 'vcr'
end

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'rb-readline'
  # gem 'factory_girl_rails'
  # gem 'rspec-rails'
  # gem 'spring-commands-rspec'
end

group :production do
  gem 'passenger'
end
