# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 058dd32ceef4add84ccf7ace58725925a505495e06c761fb68785e1d34e1fade1d0747334e7c91ca15c66ca95676c03fc57ddacf5a2b6297f7cbcc9716730101

test:
  secret_key_base: 2db1ae86cee9bc1afd8306b1dbf95ff63a9fe92729a1963388dcebb4da248991c347248657055ca7ee8c2d21dd911b59f448a356fa1183de138c585c8221ff0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
